# 단일 매개변수 화살표 함수에 항상 괄호 추가
arrowParens: "always"
# JSX 다중 행 요소의 닫는 태그를 별도 행에 배치
bracketSameLine: false
# 객체 리터럴의 중괄호 사이에 공백 추가
bracketSpacing: true
# 임베디드 코드 자동 포맷(예: Markdown 및 HTML 내의 코드)
embeddedLanguageFormatting: "auto"
# HTML 공백 민감도 무시, 공백을 중요하지 않은 내용으로 처리
htmlWhitespaceSensitivity: "ignore"
# @prettier pragma 주석 삽입 안 함
insertPragma: false
# JSX에서 큰따옴표 사용
jsxSingleQuote: false
# 한 줄당 코드의 최대 길이를 100자로 제한
printWidth: 100
# Markdown에서 원래 줄바꿈 형식 유지
proseWrap: "preserve"
# 필요한 경우에만 객체 속성에 따옴표 추가
quoteProps: "as-needed"
# 파일 시작 부분에 @prettier pragma 주석 삽입 불필요
requirePragma: false
# 문장 끝에 세미콜론 추가
semi: true
# 작은따옴표 대신 큰따옴표 사용
singleQuote: false
# 들여쓰기에 2개의 공백 사용
tabWidth: 2
# 다중 행 요소의 끝에 쉼표 추가(ES5 지원 객체, 배열 등)
trailingComma: "es5"
# 탭 대신 공백으로 들여쓰기
useTabs: false
# Vue 파일의 <script>와 <style>에 추가 들여쓰기 하지 않음
vueIndentScriptAndStyle: false
# 시스템에 따라 자동으로 줄바꿈 문자 감지
endOfLine: "auto"
# HTML 파일에 특정 포맷팅 규칙 적용
overrides:
  - files: "*.html"
    options:
      parser: "html"
